image:
  name: docker:19.03.1

stages:
  - build
  - deploy_stage
  - tag_prod
  - deploy_prod

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build_master:
  stage: build
  before_script:
  - export CURRENT_COMMIT=${CI_COMMIT_SHA::8}
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg build_env=prod -f Dockerfile --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CURRENT_COMMIT --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CURRENT_COMMIT
    - docker push $CI_REGISTRY_IMAGE:latest\
  only:
    - master
    
tag_build_prod:
  stage: tag_prod
  before_script:
  - export CURRENT_COMMIT=${CI_COMMIT_SHA::8}
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CURRENT_COMMIT || true
    - docker tag  $CI_REGISTRY_IMAGE:$CURRENT_COMMIT $CI_REGISTRY_IMAGE:prod
    - docker push $CI_REGISTRY_IMAGE:prod\
  only:
    - master
  when: manual
  tags:
    - production

deploy_staging:
  image: registry.gitlab.qsoft.ru/system-software/k8s-tool:latest
  stage: deploy_stage
  environment:
    name: staging
    url: stage.kia.ru
  script:
    - eval $(ssh-agent -s)
    - echo "$STAGE_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $STAGE_SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $STAGE_SSH_USER@$STAGE_SSH_HOST -p $STAGE_SSH_PORT "sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $STAGE_SSH_USER@$STAGE_SSH_HOST -p $STAGE_SSH_PORT "sudo docker service update --force --image  $CI_REGISTRY_IMAGE:latest $STAGE_SERVICE_NAME"
  only:
    - master
    
deploy_production:
  image: registry.gitlab.qsoft.ru/system-software/k8s-tool:latest
  stage: deploy_prod
  environment:
    name: production
    url: kia.ru
  script:
    - eval $(ssh-agent -s)
    - echo "$PROD_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $PROD_SSH_USER@$PROD_SSH_HOST -p $PROD_SSH_PORT "sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $PROD_SSH_USER@$PROD_SSH_HOST -p $PROD_SSH_PORT "sudo docker service update --force --image  $CI_REGISTRY_IMAGE:prod $PROD_SERVICE_NAME"
  only:
    - master
  when: manual
  tags:
    - production
